class MyDir:
    src = "src"
    api = "api"
    controller = "controllers"
    model = "models"
    service = "services"
    config = "config"
    server = "servers"
    doc = "doc"
    node_modules = "node_modules"
